name: wrath-rs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    name: Wrath-rs on stable rust
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: fmt
        run: cargo fmt --all
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Build
        run: cargo build --all
      - uses: actions/upload-artifact@v4
        with:
          name: wrath-rs
          path: |
            target/debug/wrath-authserver
            target/debug/wrath-worldserver
          if-no-files-found: error
